// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddAddressInput struct {
	Label         *string  `json:"label,omitempty"`
	StreetAddress string   `json:"streetAddress"`
	City          string   `json:"city"`
	County        string   `json:"county"`
	PostalCode    *string  `json:"postalCode,omitempty"`
	Floor         *string  `json:"floor,omitempty"`
	Apartment     *string  `json:"apartment,omitempty"`
	EntryCode     *string  `json:"entryCode,omitempty"`
	Latitude      *float64 `json:"latitude,omitempty"`
	Longitude     *float64 `json:"longitude,omitempty"`
	Notes         *string  `json:"notes,omitempty"`
}

type Address struct {
	ID            string       `json:"id"`
	Label         *string      `json:"label,omitempty"`
	StreetAddress string       `json:"streetAddress"`
	City          string       `json:"city"`
	County        string       `json:"county"`
	PostalCode    *string      `json:"postalCode,omitempty"`
	Floor         *string      `json:"floor,omitempty"`
	Apartment     *string      `json:"apartment,omitempty"`
	EntryCode     *string      `json:"entryCode,omitempty"`
	Coordinates   *Coordinates `json:"coordinates,omitempty"`
	Notes         *string      `json:"notes,omitempty"`
	IsDefault     bool         `json:"isDefault"`
}

type AdminUpdateCompanyInput struct {
	ID           string `json:"id"`
	CompanyName  string `json:"companyName"`
	Cui          string `json:"cui"`
	Address      string `json:"address"`
	ContactPhone string `json:"contactPhone"`
	ContactEmail string `json:"contactEmail"`
}

type AuthPayload struct {
	Token     string `json:"token"`
	User      *User  `json:"user"`
	IsNewUser bool   `json:"isNewUser"`
}

type AvailabilitySlot struct {
	ID          string `json:"id"`
	DayOfWeek   int    `json:"dayOfWeek"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	IsAvailable bool   `json:"isAvailable"`
}

type AvailabilitySlotInput struct {
	DayOfWeek   int    `json:"dayOfWeek"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	IsAvailable bool   `json:"isAvailable"`
}

type Booking struct {
	ID                     string             `json:"id"`
	ReferenceCode          string             `json:"referenceCode"`
	Client                 *User              `json:"client,omitempty"`
	Company                *Company           `json:"company,omitempty"`
	Cleaner                *CleanerProfile    `json:"cleaner,omitempty"`
	Address                *Address           `json:"address,omitempty"`
	ServiceType            ServiceType        `json:"serviceType"`
	ServiceName            string             `json:"serviceName"`
	ScheduledDate          string             `json:"scheduledDate"`
	ScheduledStartTime     string             `json:"scheduledStartTime"`
	EstimatedDurationHours float64            `json:"estimatedDurationHours"`
	PropertyType           *string            `json:"propertyType,omitempty"`
	NumRooms               *int               `json:"numRooms,omitempty"`
	NumBathrooms           *int               `json:"numBathrooms,omitempty"`
	AreaSqm                *int               `json:"areaSqm,omitempty"`
	HasPets                *bool              `json:"hasPets,omitempty"`
	SpecialInstructions    *string            `json:"specialInstructions,omitempty"`
	HourlyRate             float64            `json:"hourlyRate"`
	EstimatedTotal         float64            `json:"estimatedTotal"`
	FinalTotal             *float64           `json:"finalTotal,omitempty"`
	PlatformCommissionPct  float64            `json:"platformCommissionPct"`
	Extras                 []*BookingExtra    `json:"extras"`
	Status                 BookingStatus      `json:"status"`
	StartedAt              *time.Time         `json:"startedAt,omitempty"`
	CompletedAt            *time.Time         `json:"completedAt,omitempty"`
	CancelledAt            *time.Time         `json:"cancelledAt,omitempty"`
	CancellationReason     *string            `json:"cancellationReason,omitempty"`
	PaymentStatus          string             `json:"paymentStatus"`
	PaidAt                 *time.Time         `json:"paidAt,omitempty"`
	TimeSlots              []*BookingTimeSlot `json:"timeSlots"`
	Review                 *Review            `json:"review,omitempty"`
	ChatRoom               *ChatRoom          `json:"chatRoom,omitempty"`
	CreatedAt              time.Time          `json:"createdAt"`
}

type BookingConnection struct {
	Edges      []*Booking `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type BookingExtra struct {
	Extra    *ServiceExtra `json:"extra"`
	Price    float64       `json:"price"`
	Quantity int           `json:"quantity"`
}

type BookingTimeSlot struct {
	ID         string `json:"id"`
	SlotDate   string `json:"slotDate"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
	IsSelected bool   `json:"isSelected"`
}

type BookingsByStatus struct {
	Status BookingStatus `json:"status"`
	Count  int           `json:"count"`
}

type ChatMessage struct {
	ID          string    `json:"id"`
	Sender      *User     `json:"sender"`
	Content     string    `json:"content"`
	MessageType string    `json:"messageType"`
	IsRead      bool      `json:"isRead"`
	CreatedAt   time.Time `json:"createdAt"`
}

type ChatMessageConnection struct {
	Edges    []*ChatMessage `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ChatParticipant struct {
	User     *User     `json:"user"`
	JoinedAt time.Time `json:"joinedAt"`
}

type ChatRoom struct {
	ID           string                 `json:"id"`
	Booking      *Booking               `json:"booking,omitempty"`
	RoomType     string                 `json:"roomType"`
	Participants []*ChatParticipant     `json:"participants"`
	Messages     *ChatMessageConnection `json:"messages"`
	LastMessage  *ChatMessage           `json:"lastMessage,omitempty"`
	CreatedAt    time.Time              `json:"createdAt"`
}

type CityArea struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CityID   string `json:"cityId"`
	CityName string `json:"cityName"`
}

type CleanerDailyEarnings struct {
	Date   string  `json:"date"`
	Amount float64 `json:"amount"`
}

type CleanerDateOverride struct {
	ID          string `json:"id"`
	Date        string `json:"date"`
	IsAvailable bool   `json:"isAvailable"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
}

type CleanerPerformance struct {
	CleanerID          string  `json:"cleanerId"`
	FullName           string  `json:"fullName"`
	RatingAvg          float64 `json:"ratingAvg"`
	TotalCompletedJobs int     `json:"totalCompletedJobs"`
	ThisMonthCompleted int     `json:"thisMonthCompleted"`
	TotalEarnings      float64 `json:"totalEarnings"`
	ThisMonthEarnings  float64 `json:"thisMonthEarnings"`
}

type CleanerProfile struct {
	ID                 string              `json:"id"`
	UserID             *string             `json:"userId,omitempty"`
	User               *User               `json:"user,omitempty"`
	Company            *Company            `json:"company"`
	FullName           string              `json:"fullName"`
	Phone              *string             `json:"phone,omitempty"`
	Email              *string             `json:"email,omitempty"`
	Bio                *string             `json:"bio,omitempty"`
	AvatarURL          *string             `json:"avatarUrl,omitempty"`
	Status             CleanerStatus       `json:"status"`
	IsCompanyAdmin     bool                `json:"isCompanyAdmin"`
	InviteToken        *string             `json:"inviteToken,omitempty"`
	RatingAvg          float64             `json:"ratingAvg"`
	TotalJobsCompleted int                 `json:"totalJobsCompleted"`
	Availability       []*AvailabilitySlot `json:"availability"`
	CreatedAt          time.Time           `json:"createdAt"`
}

type CleanerStats struct {
	TotalJobsCompleted int     `json:"totalJobsCompleted"`
	AverageRating      float64 `json:"averageRating"`
	TotalReviews       int     `json:"totalReviews"`
	ThisMonthJobs      int     `json:"thisMonthJobs"`
	ThisMonthEarnings  float64 `json:"thisMonthEarnings"`
}

type CleanerSuggestion struct {
	Cleaner            *CleanerProfile `json:"cleaner"`
	Company            *Company        `json:"company"`
	AvailabilityStatus string          `json:"availabilityStatus"`
	AvailableFrom      *string         `json:"availableFrom,omitempty"`
	AvailableTo        *string         `json:"availableTo,omitempty"`
	SuggestedStartTime *string         `json:"suggestedStartTime,omitempty"`
	SuggestedEndTime   *string         `json:"suggestedEndTime,omitempty"`
	SuggestedSlotIndex *int            `json:"suggestedSlotIndex,omitempty"`
	MatchScore         float64         `json:"matchScore"`
}

type Company struct {
	ID                  string             `json:"id"`
	CompanyName         string             `json:"companyName"`
	Cui                 string             `json:"cui"`
	CompanyType         CompanyType        `json:"companyType"`
	LegalRepresentative string             `json:"legalRepresentative"`
	ContactEmail        string             `json:"contactEmail"`
	ContactPhone        string             `json:"contactPhone"`
	Address             string             `json:"address"`
	City                string             `json:"city"`
	County              string             `json:"county"`
	Description         *string            `json:"description,omitempty"`
	LogoURL             *string            `json:"logoUrl,omitempty"`
	Status              CompanyStatus      `json:"status"`
	RejectionReason     *string            `json:"rejectionReason,omitempty"`
	MaxServiceRadiusKm  int                `json:"maxServiceRadiusKm"`
	RatingAvg           float64            `json:"ratingAvg"`
	TotalJobsCompleted  int                `json:"totalJobsCompleted"`
	Documents           []*CompanyDocument `json:"documents"`
	Cleaners            []*CleanerProfile  `json:"cleaners"`
	Admin               *User              `json:"admin,omitempty"`
	CreatedAt           time.Time          `json:"createdAt"`
}

type CompanyApplicationInput struct {
	CompanyName         string      `json:"companyName"`
	Cui                 string      `json:"cui"`
	CompanyType         CompanyType `json:"companyType"`
	LegalRepresentative string      `json:"legalRepresentative"`
	ContactEmail        string      `json:"contactEmail"`
	ContactPhone        string      `json:"contactPhone"`
	Address             string      `json:"address"`
	City                string      `json:"city"`
	County              string      `json:"county"`
	Description         *string     `json:"description,omitempty"`
}

type CompanyApplicationResult struct {
	Company    *Company `json:"company"`
	ClaimToken *string  `json:"claimToken,omitempty"`
}

type CompanyConnection struct {
	Edges      []*Company `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type CompanyDocument struct {
	ID           string    `json:"id"`
	DocumentType string    `json:"documentType"`
	FileURL      string    `json:"fileUrl"`
	FileName     string    `json:"fileName"`
	UploadedAt   time.Time `json:"uploadedAt"`
}

type CompanyFinancialSummary struct {
	CompletedBookings int     `json:"completedBookings"`
	TotalRevenue      float64 `json:"totalRevenue"`
	TotalCommission   float64 `json:"totalCommission"`
	NetPayout         float64 `json:"netPayout"`
}

type CompanyPerformance struct {
	Company        *Company `json:"company"`
	TotalBookings  int      `json:"totalBookings"`
	TotalRevenue   float64  `json:"totalRevenue"`
	AverageRating  float64  `json:"averageRating"`
	CompletionRate float64  `json:"completionRate"`
}

type CompanyWorkSchedule struct {
	ID        string `json:"id"`
	DayOfWeek int    `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	IsWorkDay bool   `json:"isWorkDay"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CreateBookingInput struct {
	AddressID           *string          `json:"addressId,omitempty"`
	Address             *AddAddressInput `json:"address,omitempty"`
	ServiceType         ServiceType      `json:"serviceType"`
	ScheduledDate       *string          `json:"scheduledDate,omitempty"`
	ScheduledStartTime  *string          `json:"scheduledStartTime,omitempty"`
	TimeSlots           []*TimeSlotInput `json:"timeSlots,omitempty"`
	PropertyType        *string          `json:"propertyType,omitempty"`
	NumRooms            int              `json:"numRooms"`
	NumBathrooms        int              `json:"numBathrooms"`
	AreaSqm             *int             `json:"areaSqm,omitempty"`
	HasPets             *bool            `json:"hasPets,omitempty"`
	SpecialInstructions *string          `json:"specialInstructions,omitempty"`
	Extras              []*ExtraInput    `json:"extras,omitempty"`
	GuestEmail          *string          `json:"guestEmail,omitempty"`
	GuestName           *string          `json:"guestName,omitempty"`
	GuestPhone          *string          `json:"guestPhone,omitempty"`
	PreferredCleanerID  *string          `json:"preferredCleanerId,omitempty"`
	SuggestedStartTime  *string          `json:"suggestedStartTime,omitempty"`
}

type CreateServiceDefinitionInput struct {
	ServiceType        ServiceType `json:"serviceType"`
	NameRo             string      `json:"nameRo"`
	NameEn             string      `json:"nameEn"`
	BasePricePerHour   float64     `json:"basePricePerHour"`
	MinHours           float64     `json:"minHours"`
	HoursPerRoom       float64     `json:"hoursPerRoom"`
	HoursPerBathroom   float64     `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64     `json:"hoursPer100Sqm"`
	HouseMultiplier    float64     `json:"houseMultiplier"`
	PetDurationMinutes int         `json:"petDurationMinutes"`
	IsActive           bool        `json:"isActive"`
}

type CreateServiceExtraInput struct {
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	IsActive        bool    `json:"isActive"`
}

type DailyRevenue struct {
	Date         string  `json:"date"`
	BookingCount int     `json:"bookingCount"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
}

type EnabledCity struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	County   string      `json:"county"`
	IsActive bool        `json:"isActive"`
	Areas    []*CityArea `json:"areas"`
}

type ExtraInput struct {
	ExtraID  string `json:"extraId"`
	Quantity int    `json:"quantity"`
}

type ExtraLineItem struct {
	Extra     *ServiceExtra `json:"extra"`
	Quantity  int           `json:"quantity"`
	LineTotal float64       `json:"lineTotal"`
}

type InviteCleanerInput struct {
	FullName string  `json:"fullName"`
	Email    string  `json:"email"`
	Phone    *string `json:"phone,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	Data      map[string]any `json:"data,omitempty"`
	IsRead    bool           `json:"isRead"`
	CreatedAt time.Time      `json:"createdAt"`
}

type NotificationConnection struct {
	Edges      []*Notification `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PaymentMethod struct {
	ID           string `json:"id"`
	CardLastFour string `json:"cardLastFour"`
	CardBrand    string `json:"cardBrand"`
	IsDefault    bool   `json:"isDefault"`
}

type PlatformSetting struct {
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	ValueType   string    `json:"valueType"`
	Description *string   `json:"description,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type PlatformStats struct {
	TotalClients            int     `json:"totalClients"`
	TotalCompanies          int     `json:"totalCompanies"`
	TotalCleaners           int     `json:"totalCleaners"`
	TotalBookings           int     `json:"totalBookings"`
	TotalRevenue            float64 `json:"totalRevenue"`
	PlatformCommissionTotal float64 `json:"platformCommissionTotal"`
	AverageRating           float64 `json:"averageRating"`
	BookingsThisMonth       int     `json:"bookingsThisMonth"`
	RevenueThisMonth        float64 `json:"revenueThisMonth"`
	NewClientsThisMonth     int     `json:"newClientsThisMonth"`
	NewCompaniesThisMonth   int     `json:"newCompaniesThisMonth"`
}

type PlatformTotals struct {
	TotalCompleted  int     `json:"totalCompleted"`
	TotalBookings   int     `json:"totalBookings"`
	TotalRevenue    float64 `json:"totalRevenue"`
	TotalCommission float64 `json:"totalCommission"`
	UniqueClients   int     `json:"uniqueClients"`
	ActiveCompanies int     `json:"activeCompanies"`
}

type PriceEstimate struct {
	HourlyRate         float64          `json:"hourlyRate"`
	EstimatedHours     float64          `json:"estimatedHours"`
	PropertyMultiplier float64          `json:"propertyMultiplier"`
	PetsSurcharge      float64          `json:"petsSurcharge"`
	Subtotal           float64          `json:"subtotal"`
	Extras             []*ExtraLineItem `json:"extras"`
	Total              float64          `json:"total"`
}

type PriceEstimateInput struct {
	ServiceType  ServiceType   `json:"serviceType"`
	NumRooms     int           `json:"numRooms"`
	NumBathrooms int           `json:"numBathrooms"`
	AreaSqm      *int          `json:"areaSqm,omitempty"`
	PropertyType *string       `json:"propertyType,omitempty"`
	HasPets      *bool         `json:"hasPets,omitempty"`
	Extras       []*ExtraInput `json:"extras,omitempty"`
}

type Query struct {
}

type RevenueByMonth struct {
	Month        string  `json:"month"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
	BookingCount int     `json:"bookingCount"`
}

type Review struct {
	ID         string    `json:"id"`
	Booking    *Booking  `json:"booking,omitempty"`
	Reviewer   *User     `json:"reviewer,omitempty"`
	Rating     int       `json:"rating"`
	Comment    *string   `json:"comment,omitempty"`
	ReviewType string    `json:"reviewType"`
	CreatedAt  time.Time `json:"createdAt"`
}

type ReviewConnection struct {
	Reviews    []*Review `json:"reviews"`
	TotalCount int       `json:"totalCount"`
}

type ServiceDefinition struct {
	ID                 string      `json:"id"`
	ServiceType        ServiceType `json:"serviceType"`
	NameRo             string      `json:"nameRo"`
	NameEn             string      `json:"nameEn"`
	DescriptionRo      *string     `json:"descriptionRo,omitempty"`
	DescriptionEn      *string     `json:"descriptionEn,omitempty"`
	BasePricePerHour   float64     `json:"basePricePerHour"`
	MinHours           float64     `json:"minHours"`
	HoursPerRoom       float64     `json:"hoursPerRoom"`
	HoursPerBathroom   float64     `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64     `json:"hoursPer100Sqm"`
	HouseMultiplier    float64     `json:"houseMultiplier"`
	PetDurationMinutes int         `json:"petDurationMinutes"`
	Icon               *string     `json:"icon,omitempty"`
	IsActive           bool        `json:"isActive"`
}

type ServiceExtra struct {
	ID              string  `json:"id"`
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	Icon            *string `json:"icon,omitempty"`
	IsActive        bool    `json:"isActive"`
}

type ServiceRevenue struct {
	ServiceType  ServiceType `json:"serviceType"`
	BookingCount int         `json:"bookingCount"`
	Revenue      float64     `json:"revenue"`
}

type SubmitReviewInput struct {
	BookingID string  `json:"bookingId"`
	Rating    int     `json:"rating"`
	Comment   *string `json:"comment,omitempty"`
}

type Subscription struct {
}

type TimeSlotInput struct {
	Date      string `json:"date"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type TopCompany struct {
	ID           string  `json:"id"`
	CompanyName  string  `json:"companyName"`
	BookingCount int     `json:"bookingCount"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
}

type UpdateAddressInput struct {
	Label         *string  `json:"label,omitempty"`
	StreetAddress *string  `json:"streetAddress,omitempty"`
	City          *string  `json:"city,omitempty"`
	County        *string  `json:"county,omitempty"`
	PostalCode    *string  `json:"postalCode,omitempty"`
	Floor         *string  `json:"floor,omitempty"`
	Apartment     *string  `json:"apartment,omitempty"`
	EntryCode     *string  `json:"entryCode,omitempty"`
	Latitude      *float64 `json:"latitude,omitempty"`
	Longitude     *float64 `json:"longitude,omitempty"`
	Notes         *string  `json:"notes,omitempty"`
}

type UpdateCleanerProfileInput struct {
	Phone *string `json:"phone,omitempty"`
	Bio   *string `json:"bio,omitempty"`
}

type UpdateCompanyInput struct {
	Description        *string                 `json:"description,omitempty"`
	ContactPhone       *string                 `json:"contactPhone,omitempty"`
	ContactEmail       *string                 `json:"contactEmail,omitempty"`
	MaxServiceRadiusKm *int                    `json:"maxServiceRadiusKm,omitempty"`
	WorkSchedule       []*WorkScheduleDayInput `json:"workSchedule,omitempty"`
}

type UpdateProfileInput struct {
	FullName          *string `json:"fullName,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	AvatarURL         *string `json:"avatarUrl,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
}

type UpdateServiceDefinitionInput struct {
	ID                 string  `json:"id"`
	NameRo             string  `json:"nameRo"`
	NameEn             string  `json:"nameEn"`
	BasePricePerHour   float64 `json:"basePricePerHour"`
	MinHours           float64 `json:"minHours"`
	HoursPerRoom       float64 `json:"hoursPerRoom"`
	HoursPerBathroom   float64 `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64 `json:"hoursPer100Sqm"`
	HouseMultiplier    float64 `json:"houseMultiplier"`
	PetDurationMinutes int     `json:"petDurationMinutes"`
	IsActive           bool    `json:"isActive"`
}

type UpdateServiceExtraInput struct {
	ID              string  `json:"id"`
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	IsActive        bool    `json:"isActive"`
}

type UploadResult struct {
	URL      string `json:"url"`
	FileName string `json:"fileName"`
}

type User struct {
	ID                string     `json:"id"`
	Email             string     `json:"email"`
	FullName          string     `json:"fullName"`
	Phone             *string    `json:"phone,omitempty"`
	AvatarURL         *string    `json:"avatarUrl,omitempty"`
	Role              UserRole   `json:"role"`
	Status            UserStatus `json:"status"`
	PreferredLanguage string     `json:"preferredLanguage"`
	CreatedAt         time.Time  `json:"createdAt"`
}

type UserConnection struct {
	Users      []*User `json:"users"`
	TotalCount int     `json:"totalCount"`
}

type WorkScheduleDayInput struct {
	DayOfWeek int    `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	IsWorkDay bool   `json:"isWorkDay"`
}

type BookingStatus string

const (
	BookingStatusPending            BookingStatus = "PENDING"
	BookingStatusAssigned           BookingStatus = "ASSIGNED"
	BookingStatusConfirmed          BookingStatus = "CONFIRMED"
	BookingStatusInProgress         BookingStatus = "IN_PROGRESS"
	BookingStatusCompleted          BookingStatus = "COMPLETED"
	BookingStatusCancelledByClient  BookingStatus = "CANCELLED_BY_CLIENT"
	BookingStatusCancelledByCompany BookingStatus = "CANCELLED_BY_COMPANY"
	BookingStatusCancelledByAdmin   BookingStatus = "CANCELLED_BY_ADMIN"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusPending,
	BookingStatusAssigned,
	BookingStatusConfirmed,
	BookingStatusInProgress,
	BookingStatusCompleted,
	BookingStatusCancelledByClient,
	BookingStatusCancelledByCompany,
	BookingStatusCancelledByAdmin,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusPending, BookingStatusAssigned, BookingStatusConfirmed, BookingStatusInProgress, BookingStatusCompleted, BookingStatusCancelledByClient, BookingStatusCancelledByCompany, BookingStatusCancelledByAdmin:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CleanerStatus string

const (
	CleanerStatusInvited   CleanerStatus = "INVITED"
	CleanerStatusActive    CleanerStatus = "ACTIVE"
	CleanerStatusInactive  CleanerStatus = "INACTIVE"
	CleanerStatusSuspended CleanerStatus = "SUSPENDED"
)

var AllCleanerStatus = []CleanerStatus{
	CleanerStatusInvited,
	CleanerStatusActive,
	CleanerStatusInactive,
	CleanerStatusSuspended,
}

func (e CleanerStatus) IsValid() bool {
	switch e {
	case CleanerStatusInvited, CleanerStatusActive, CleanerStatusInactive, CleanerStatusSuspended:
		return true
	}
	return false
}

func (e CleanerStatus) String() string {
	return string(e)
}

func (e *CleanerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CleanerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CleanerStatus", str)
	}
	return nil
}

func (e CleanerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CleanerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CleanerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyStatus string

const (
	CompanyStatusPendingReview CompanyStatus = "PENDING_REVIEW"
	CompanyStatusApproved      CompanyStatus = "APPROVED"
	CompanyStatusRejected      CompanyStatus = "REJECTED"
	CompanyStatusSuspended     CompanyStatus = "SUSPENDED"
)

var AllCompanyStatus = []CompanyStatus{
	CompanyStatusPendingReview,
	CompanyStatusApproved,
	CompanyStatusRejected,
	CompanyStatusSuspended,
}

func (e CompanyStatus) IsValid() bool {
	switch e {
	case CompanyStatusPendingReview, CompanyStatusApproved, CompanyStatusRejected, CompanyStatusSuspended:
		return true
	}
	return false
}

func (e CompanyStatus) String() string {
	return string(e)
}

func (e *CompanyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyStatus", str)
	}
	return nil
}

func (e CompanyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyType string

const (
	CompanyTypeSrl CompanyType = "SRL"
	CompanyTypePfa CompanyType = "PFA"
	CompanyTypeIi  CompanyType = "II"
)

var AllCompanyType = []CompanyType{
	CompanyTypeSrl,
	CompanyTypePfa,
	CompanyTypeIi,
}

func (e CompanyType) IsValid() bool {
	switch e {
	case CompanyTypeSrl, CompanyTypePfa, CompanyTypeIi:
		return true
	}
	return false
}

func (e CompanyType) String() string {
	return string(e)
}

func (e *CompanyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyType", str)
	}
	return nil
}

func (e CompanyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceType string

const (
	ServiceTypeStandardCleaning  ServiceType = "STANDARD_CLEANING"
	ServiceTypeDeepCleaning      ServiceType = "DEEP_CLEANING"
	ServiceTypeMoveInOutCleaning ServiceType = "MOVE_IN_OUT_CLEANING"
	ServiceTypePostConstruction  ServiceType = "POST_CONSTRUCTION"
	ServiceTypeOfficeCleaning    ServiceType = "OFFICE_CLEANING"
	ServiceTypeWindowCleaning    ServiceType = "WINDOW_CLEANING"
)

var AllServiceType = []ServiceType{
	ServiceTypeStandardCleaning,
	ServiceTypeDeepCleaning,
	ServiceTypeMoveInOutCleaning,
	ServiceTypePostConstruction,
	ServiceTypeOfficeCleaning,
	ServiceTypeWindowCleaning,
}

func (e ServiceType) IsValid() bool {
	switch e {
	case ServiceTypeStandardCleaning, ServiceTypeDeepCleaning, ServiceTypeMoveInOutCleaning, ServiceTypePostConstruction, ServiceTypeOfficeCleaning, ServiceTypeWindowCleaning:
		return true
	}
	return false
}

func (e ServiceType) String() string {
	return string(e)
}

func (e *ServiceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceType", str)
	}
	return nil
}

func (e ServiceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleClient       UserRole = "CLIENT"
	UserRoleCompanyAdmin UserRole = "COMPANY_ADMIN"
	UserRoleCleaner      UserRole = "CLEANER"
	UserRoleGlobalAdmin  UserRole = "GLOBAL_ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleClient,
	UserRoleCompanyAdmin,
	UserRoleCleaner,
	UserRoleGlobalAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleClient, UserRoleCompanyAdmin, UserRoleCleaner, UserRoleGlobalAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
	UserStatusPending   UserStatus = "PENDING"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
	UserStatusPending,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended, UserStatusPending:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
