# Cloud Build configuration for automated deployment
# Triggered by GitHub push to 'development' or 'main' branches

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/helpmeclean-backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/helpmeclean-backend:${_ENV}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/helpmeclean-backend:latest-${_ENV}'
      - '.'
    dir: 'backend'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/helpmeclean-backend'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/helpmeclean-backend:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=${_TIMEOUT}'
      - '--concurrency=${_CONCURRENCY}'
      - '--port=8080'
      - '--set-env-vars=ENVIRONMENT=${_ENV},GCS_PROJECT_ID=${PROJECT_ID}'
      - '--set-secrets=DATABASE_URL=${_ENV}_DATABASE_URL:latest,JWT_SECRET=${_ENV}_JWT_SECRET:latest,GOOGLE_CLIENT_ID=${_ENV}_GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_ID_IOS=${_ENV}_GOOGLE_CLIENT_ID_IOS:latest,GOOGLE_CLIENT_ID_ANDROID=${_ENV}_GOOGLE_CLIENT_ID_ANDROID:latest,STRIPE_SECRET_KEY=${_ENV}_STRIPE_SECRET_KEY:latest,STRIPE_PUBLISHABLE_KEY=${_ENV}_STRIPE_PUBLISHABLE_KEY:latest,STRIPE_WEBHOOK_SECRET=${_ENV}_STRIPE_WEBHOOK_SECRET:latest,FACTUREAZA_API_KEY=${_ENV}_FACTUREAZA_API_KEY:latest,GCS_BUCKET=${_ENV}_GCS_BUCKET:latest,FIREBASE_SERVICE_ACCOUNT_KEY=${_ENV}_FIREBASE_SERVICE_ACCOUNT_KEY:latest'
      - '--set-env-vars=^@^JWT_EXPIRY=24h@FACTUREAZA_API_URL=https://sandbox.factureaza.ro/api/v1/@PLATFORM_COMPANY_NAME=HelpMeClean SRL@PLATFORM_CUI=${_PLATFORM_CUI}@PLATFORM_REG_NUMBER=${_PLATFORM_REG_NUMBER}@PLATFORM_ADDRESS=${_PLATFORM_ADDRESS}@PLATFORM_CITY=${_PLATFORM_CITY}@PLATFORM_COUNTY=${_PLATFORM_COUNTY}@PLATFORM_IS_VAT_PAYER=${_PLATFORM_IS_VAT_PAYER}@PLATFORM_BANK_NAME=${_PLATFORM_BANK_NAME}@PLATFORM_IBAN=${_PLATFORM_IBAN}@STRIPE_CONNECT_RETURN_URL=${_STRIPE_CONNECT_RETURN_URL}@STRIPE_CONNECT_REFRESH_URL=${_STRIPE_CONNECT_REFRESH_URL}@ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'
    waitFor: ['push-image']

# Substitution variables (defaults for development)
substitutions:
  _REGION: 'europe-central2'
  _ARTIFACT_REGISTRY_REPO: 'helpmeclean'
  _ENV: 'dev'
  _SERVICE_NAME: 'helpmeclean-backend-dev'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '300'
  _CONCURRENCY: '80'
  # Platform details (same for dev/prod)
  _PLATFORM_CUI: 'RO12345678'
  _PLATFORM_REG_NUMBER: 'J40/1234/2024'
  _PLATFORM_ADDRESS: 'Str. Exemplu nr. 1'
  _PLATFORM_CITY: 'Bucuresti'
  _PLATFORM_COUNTY: 'Bucuresti'
  _PLATFORM_IS_VAT_PAYER: 'true'
  _PLATFORM_BANK_NAME: 'ING Bank'
  _PLATFORM_IBAN: 'RO49AAAA1B31007593840000'
  # URLs for dev environment (will be Cloud Run URLs after first deploy)
  _STRIPE_CONNECT_RETURN_URL: 'http://localhost:3000/firma/setari?stripe=complete'
  _STRIPE_CONNECT_REFRESH_URL: 'http://localhost:3000/firma/setari?stripe=refresh'
  _ALLOWED_ORIGINS: 'http://localhost:3000'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
